name: Build and Deploy
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"
permissions:
  contents: write
jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
      - uses: actions/setup-node@v5
        with:
          node-version: 16

      - name: Install and Build 🔧
        run: |
          yarn
          yarn build -- --base=/cfpb-uswds/

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist/
